version: "3"
services:
  content:
    container_name: content-service
    build: ./packages/content
    ports:
      - 4001:4000
  customer:
    container_name: customer-service
    build: ./packages/customer
    ports:
      - 4002:4000
  search:
    container_name: search-service
    build: ./packages/search
    ports:
      - 4003:4000
  gateway:
    container_name: gql-gateway
    build: ./packages/gateway
    ports:
      - 4000:4000
    links:
      - content
      - customer
      - search
